### ISSUE TITLE
file system permission checks and restrictions

### ISSUE THREAD

**Issue by matu3ba** [matu3ba/sandboxamples#11]
#### TODO
- [ ] finish windows acl including user permission lookups in https://github.com/matu3ba/sandboxamples/blob/master/test/win/main_ACL.zig
- [ ] test: compare results with powershell get-acl https://learn.microsoft.com/de-de/powershell/module/microsoft.powershell.security/get-acl?view=powershell-7.4
- [ ] figure out good way to prevent footgun of setting NULL allowing all users to do everything (in api?), TODO explanation
- [ ] write a list of all filepath types on windows and figure out how to restrict access to them (UNC etc)

#### general improvements
- [ ] restrict ETW output of specific program to create sandboxing rules enforced by CI for running as impersonated lower privileged user
- [ ] ci tests: create another user and use it for checking file permissions
